# Development code - SVM

We start development by using a smaller and more manageable data set to figure out what a piece of code is actually doing or to test out a new piece of code before applying it to larger datasets.


In [18]:
import random
import numpy as np

# Some more magic so that the notebook will reload external python modules;
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

# Evaluate the naive implementation of the loss we provided for you:
from cs231n.classifiers.linear_svm_V1 import svm_loss_naive

# Use a smaller dataset to code svm_loss_naive 
# We will first try a small training dataset with only 5 data points and 3 classes
X1 = np.random.randn(5, 4)
W1 = np.random.randn(4, 3)
y1 = np.array([1, 2, 0, 0, 1])
S = X1.dot(W1)
print "Training Data:\n"
print X1
print "\n Parameters:"
print W1
print "\nTrue Labels:"
print y1
print "\nScore (XW):"
print S



The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Training Data:

[[ 0.57442478  1.0679959  -0.50499719 -0.83689563]
 [-1.0161851  -0.07748431 -1.38694829  0.09319964]
 [ 0.25843924  0.39654861  0.8764847   1.99541077]
 [-0.8556697   0.53403462 -0.67092401  0.18207436]
 [ 0.02367122 -1.11203876  0.26283394 -0.27124496]]

 Parameters:
[[-0.31691947 -0.39810944  0.85919763]
 [ 0.95308924 -0.63623584  1.56948124]
 [ 0.67043001 -0.20444275  0.19902715]
 [ 0.78041851  0.89132826 -0.43489747]]

True Labels:
[1 2 0 0 1]

Score (XW):
[[-0.15584511 -1.5508869   2.43319958]
 [-0.60891765  0.82047416 -1.31128664]
 [ 2.44091895  1.24418953  0.15107114]
 [ 0.47244765  0.30033179 -0.10974783]
 [-1.10284687  0.40259238 -1.55471088]]


In [19]:
loss, grad = svm_loss_naive(W1, X1, y1, 0.1, True)

print "Outputs of svm_loss_naive:\n"
print loss
print grad

Training data 0 - Forward Pass

[-0.15584511 -1.5508869   2.43319958]
-1.55088690054
[ 2.39504179  0.          4.98408648]
[ 2.39504179  0.          4.98408648]
[ 1.  0.  1.]
7.37912827505
Training data 1 - Forward Pass

[-0.60891765  0.82047416 -1.31128664]
-1.31128664461
[ 1.70236899  3.1317608   0.        ]
[ 1.70236899  3.1317608   0.        ]
[ 1.  1.  0.]
4.83412979912
Training data 2 - Forward Pass

[ 2.44091895  1.24418953  0.15107114]
2.44091894682
[ 0.         -0.19672942 -1.2898478 ]
[ 0.  0.  0.]
[ 0.  0.  0.]
0.0
Training data 3 - Forward Pass

[ 0.47244765  0.30033179 -0.10974783]
0.472447649855
[ 0.          0.82788414  0.41780452]
[ 0.          0.82788414  0.41780452]
[ 0.  1.  1.]
1.24568865799
Training data 4 - Forward Pass

[-1.10284687  0.40259238 -1.55471088]
0.402592380905
[-0.50543925  0.         -0.95730326]
[ 0.  0.  0.]
[ 0.  0.  0.]
0.0

These following two numbers should be equal
2.69178934643
2.69178934643
0.344856805919
3.03664615235
Training data 0 - Back

Run gradient check

In [30]:
from cs231n.gradient_check import grad_check_sparse

loss, grad = svm_loss_naive(W1, X1, y1, 0.5, False)

print '\n'+'Numerical gradient calculation' 
f = lambda w: svm_loss_naive(W1, X1, y1, 0.5, False)[0]
grad_numerical = grad_check_sparse(f, W1, grad, 3)


Numerical gradient calculation
numerical: 0.835477 analytic: 0.835477, relative error: 6.458937e-12
numerical: 0.835477 analytic: 0.835477, relative error: 6.458937e-12
numerical: 0.835477 analytic: 0.835477, relative error: 6.458937e-12


In [61]:
from cs231n.classifiers.linear_svm_V1 import svm_loss_vectorized

print "Vectorized Implementation"
loss, grad = svm_loss_vectorized(W1, X1, y1, 0.0, True)

print "Naive Implementation"
loss, grad = svm_loss_naive(W1, X1, y1, 0.0, True)

Vectorized Implementation
Training data %d - Forward Pass

Parameters:
[[-0.31691947 -0.39810944  0.85919763]
 [ 0.95308924 -0.63623584  1.56948124]
 [ 0.67043001 -0.20444275  0.19902715]
 [ 0.78041851  0.89132826 -0.43489747]]

Training Data:
[[ 0.57442478  1.0679959  -0.50499719 -0.83689563]
 [-1.0161851  -0.07748431 -1.38694829  0.09319964]
 [ 0.25843924  0.39654861  0.8764847   1.99541077]
 [-0.8556697   0.53403462 -0.67092401  0.18207436]
 [ 0.02367122 -1.11203876  0.26283394 -0.27124496]]

True Labels:
[1 2 0 0 1]

Score (XW):
[[-0.15584511 -1.5508869   2.43319958]
 [-0.60891765  0.82047416 -1.31128664]
 [ 2.44091895  1.24418953  0.15107114]
 [ 0.47244765  0.30033179 -0.10974783]
 [-1.10284687  0.40259238 -1.55471088]]
[-1.5508869  -1.31128664  2.44091895  0.47244765  0.40259238]
[ 1.5508869   1.31128664 -2.44091895 -0.47244765 -0.40259238]
[[ 2.39504179  0.          4.98408648]
 [ 1.70236899  3.1317608   0.        ]
 [ 0.         -0.19672942 -1.2898478 ]
 [ 0.          0.8278841

In [92]:
from cs231n.classifiers.linear_svm_V1 import svm_loss_vectorized

loss, grad = svm_loss_naive(W1, X1, y1, 0.5, True)
print loss

loss, grad = svm_loss_vectorized(W1, X1, y1, 0.5, True)
print loss

print '\n'+'Numerical gradient calculation' 
f = lambda w: svm_loss_vectorized(W1, X1, y1, 0.5, False)[0]
grad_numerical = grad_check_sparse(f, W1, grad, 3)

Training data 0 - Forward Pass

[-0.15584511 -1.5508869   2.43319958]
-1.55088690054
[ 2.39504179  0.          4.98408648]
[ 2.39504179  0.          4.98408648]
[ 1.  0.  1.]
7.37912827505
Training data 1 - Forward Pass

[-0.60891765  0.82047416 -1.31128664]
-1.31128664461
[ 1.70236899  3.1317608   0.        ]
[ 1.70236899  3.1317608   0.        ]
[ 1.  1.  0.]
4.83412979912
Training data 2 - Forward Pass

[ 2.44091895  1.24418953  0.15107114]
2.44091894682
[ 0.         -0.19672942 -1.2898478 ]
[ 0.  0.  0.]
[ 0.  0.  0.]
0.0
Training data 3 - Forward Pass

[ 0.47244765  0.30033179 -0.10974783]
0.472447649855
[ 0.          0.82788414  0.41780452]
[ 0.          0.82788414  0.41780452]
[ 0.  1.  1.]
1.24568865799
Training data 4 - Forward Pass

[-1.10284687  0.40259238 -1.55471088]
0.402592380905
[-0.50543925  0.         -0.95730326]
[ 0.  0.  0.]
[ 0.  0.  0.]
0.0

These following two numbers should be equal
2.69178934643
2.69178934643
1.72428402959
4.41607337602
Training data 0 - Backw

# Development code - Softmax

We start development by using a smaller and more manageable data set to figure out what a piece of code is actually doing or to test out a new piece of code before applying it to larger datasets.

In [173]:
# First implement the naive softmax loss function with nested loops.
# Open the file cs231n/classifiers/softmax.py and implement the
# softmax_loss_naive function.

# Use a smaller dataset to code svm_loss_naive 
# We will first try a small training dataset with only 5 data points and 3 classes
X1 = np.random.randn(5, 4)
W1 = np.random.randn(4, 3)
"""
X1 = np.array([[1.0,0,2.0,1.0],
              [0,1.0,3.0,2.0],
              [2.0,3.0,4.0,1.0],
              [0,0,2.0,3.0]])
W1 = np.array([[2.0,2.0,3.0],
              [3.0,3.0,3.0],
              [0,0,0],
              [1.0,1.0,1.0]])
"""

y1 = np.array([1, 2, 0, 0, 1])

print X1
print X1.dtype
print W1
print W1.dtype
print y1

from cs231n.classifiers.softmax import softmax_loss_naive

loss, grad = softmax_loss_naive(W1, X1, y1, 0.0, True)
print loss
print grad

[[-1.06468274  0.09728655 -0.98904076  1.2305726 ]
 [ 0.91878574 -1.41662552 -0.17210046  0.21351515]
 [ 0.84495807  1.19061162 -0.1311505  -0.03793197]
 [ 1.11992998  0.76793865  0.70910003  2.25192427]
 [-1.01017972 -1.14507688 -0.81452389 -0.16170988]]
float64
[[ 0.43184044  0.86656964  0.73077787]
 [ 0.22107617  1.38770271  0.64829212]
 [ 0.49143095  1.27202316 -1.04341634]
 [ 0.20637279 -0.0477959   0.53545559]]
float64
[1 2 0 0 1]
Training data - Forward Pass

 Scores:
[[-0.67035386 -2.104516    0.97592179]
 [ 0.04307491 -1.39878416  0.04694144]
 [ 0.55582338  2.2194165   1.50587448]
 [ 1.46661358  2.83052678  1.78218749]
 [-1.12304043 -3.49278155 -0.71726223]]

 Scaling Constant:
-0.717262226852

 Normalized Scores:
[[-1.64627565 -3.08043779  0.        ]
 [-0.00386653 -1.44572561  0.        ]
 [-1.66359312  0.         -0.71354202]
 [-1.3639132   0.         -1.04833929]
 [-0.4057782  -2.77551932  0.        ]]

 Scores of correct classes:
[-3.08043779  0.         -1.66359312 -1.36

In [175]:
from cs231n.gradient_check import grad_check_sparse

# As we did for the SVM, use numeric gradient checking as a debugging tool.
# The numeric gradient should be close to the analytic gradient.

loss, grad = softmax_loss_naive(W1, X1, y1, 0.5, False)
f = lambda w: softmax_loss_naive(w, X1, y1, 0.5, False)[0]
grad_numerical = grad_check_sparse(f, W1, grad, 10)

numerical: 1.103385 analytic: 1.103385, relative error: 1.276301e-11
numerical: 0.040793 analytic: 0.040793, relative error: 2.600471e-10
numerical: 0.520213 analytic: 0.520213, relative error: 5.028954e-12
numerical: 0.520213 analytic: 0.520213, relative error: 5.028954e-12
numerical: -0.223886 analytic: -0.223886, relative error: 6.674119e-11
numerical: 0.466735 analytic: 0.466735, relative error: 3.222738e-11
numerical: -0.223886 analytic: -0.223886, relative error: 6.674119e-11
numerical: 1.092556 analytic: 1.092556, relative error: 6.121005e-12
numerical: 1.052560 analytic: 1.052560, relative error: 1.495102e-11
numerical: 1.052560 analytic: 1.052560, relative error: 1.495102e-11


In [178]:
from cs231n.classifiers.softmax import softmax_loss_vectorized

print "Vectorized Implementation"
loss, grad = softmax_loss_vectorized(W1, X1, y1, 0.0, False)
print loss
print grad

print "Naive Implementation"
loss, grad = softmax_loss_naive(W1, X1, y1, 0.0, False)
print loss
print grad

Vectorized Implementation
2.28799722278
[[-0.36726305  0.65927088 -0.29200783]
 [-0.55212298  0.40953355  0.14258943]
 [-0.20492291  0.41654891 -0.211626  ]
 [-0.32707287  0.0745872   0.25248568]]
Naive Implementation
2.28799722278
[[-0.36726305  0.65927088 -0.29200783]
 [-0.55212298  0.40953355  0.14258943]
 [-0.20492291  0.41654891 -0.211626  ]
 [-0.32707287  0.0745872   0.25248568]]


In [182]:
print softmax_loss_naive.__doc__
print svm_loss_naive.__doc__



  Softmax loss function, naive implementation (with loops)

  Inputs have dimension D, there are C classes, and we operate on minibatches
  of N examples.

  Inputs:
  - W: A numpy array of shape (D, C) containing weights.
  - X: A numpy array of shape (N, D) containing a minibatch of data.
  - y: A numpy array of shape (N,) containing training labels; y[i] = c means
    that X[i] has label c, where 0 <= c < C.
  - reg: (float) regularization strength

  Returns a tuple of:
  - loss as single float
  - gradient with respect to weights W; an array of same shape as W
  

  Structured SVM loss function, naive implementation (with loops).

  Inputs have dimension D, there are C classes, and we operate on minibatches
  of N examples.

  Inputs:
  - W: A numpy array of shape (D, C) containing weights.
  - X: A numpy array of shape (N, D) containing a minibatch of data.
  - y: A numpy array of shape (N,) containing training labels; y[i] = c means
    that X[i] has label c, where 0 <= c < C.


# Development code - 2 Layer NN
We start development by using a smaller and more manageable data set to figure out what a piece of code is actually doing or to test out a new piece of code before applying it to larger datasets. 